Improve support for language files

diff --git a/include/parameters b/include/parameters
--- a/include/parameters
+++ b/include/parameters
@@ -40,6 +40,10 @@
                         "unit-tests")
                             MODE="run-unit-tests"
                         ;;
+                        *)
+                            echo "Unknown 'run' command: $2"
+                            exit 1
+                        ;;
                     esac
                   else
                     echo "Error: Need a target to run"
@@ -47,6 +51,27 @@
                     echo "Examples:"
                     echo "$0 run linters"
                     echo "$0 run tests"
+                    exit 1
+                fi
+            ;;
+
+            # Helpers first
+            update)
+                if [ $# -ge 2 ]; then
+                    case $2 in
+                        "language-files")
+                            MODE="update-language-files"
+                        ;;
+                        *)
+                            echo "Unknown 'update' command: $2"
+                            exit 1
+                        ;;
+                    esac
+                  else
+                    echo "Error: Need a target to run"
+                    echo " "
+                    echo "Examples:"
+                    echo "$0 update language-files"
                     exit 1
                 fi
             ;;
